import type { Metadata } from "next";
import { cookies } from "next/headers";
import { tokenServiceFactory } from "@/factories/tokenServiceFactory";
import { redirect } from "next/navigation";
import { AppSidebar } from "@/components/AppSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tokenService = await tokenServiceFactory;

export default async function SecureLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const authToken = cookieStore.get("authToken")?.value;
  const result = await tokenService.validate(authToken || "");
  const sidebarCollapsed =
    cookieStore.get("sidebar_collapsed")?.value === "true";

  if (result == null) {
    redirect("/login");
  }

  return (
    <section className="flex h-screen overflow-hidden">
      {/* Sidebar com estado inicial vindo do Cookie (SSR) */}
      <AppSidebar initialCollapsed={sidebarCollapsed} />

      {/* Área Segura do Jogador */}
      <main className="flex-1 overflow-y-auto bg-zinc-900 text-zinc-100 p-4 md:p-6 lg:p-8 scrollbar-thin scrollbar-thumb-zinc-700 scrollbar-track-transparent">
        {children}
      </main>
    </section>
  );
}
